demo1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from exam.views import index
from users.views import login_user

# from demo1.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('accounts/login/', login_user),
    path('exam/', include('exam.urls', namespace="exam")),
    path('user/', include('users.urls', namespace="users"))  # http://127.0.0.1:9000/exam/
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exam/urls.py
from django.contrib import admin
from django.urls import path
from exam.views import *


app_name = 'exam'

urlpatterns = [
    path('home/', home, name='home'),
    path('contact/', contact, name="contact"),
    path('about/', about, name="about"),
    path('questions/list/', questions_list, name="questions_list"),
    path('question/<int:id>/delete/', delete_question, name="delete_question"),
    path('questions/create/', create_question, name="create_question"),
    path('question/<int:id>/update/', update_question, name="update_question"),
]

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),


]

exam/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
    	return self.name


class Question(models.Model):

    name = models.CharField(max_length=1000, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    choice = models.ForeignKey('exam.Choice', on_delete='SET_NULL',
                               null=True, blank=True, related_name='choice')
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name


class Choice(models.Model):
    choice_text = models.CharField(max_length=100, unique=True)
    question = models.ForeignKey(
        Question, on_delete='SET_NULL', null=True, blank=True, related_name='question')

    def __str__(self):
        return str(self.choice_text) + " -- " + str(self.question)

exam/forms.py
from django import forms
from exam.models import Question
from django.contrib.auth.models import User


class QuestionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"
            self.fields[field].widget.attrs["placeholder"] = self.fields[field].label
        self.fields['choice'].widget.attrs["class"] = "selectpicker"
        self.fields['tags'].widget.attrs["class"] = "select2"

    class Meta:
        model = Question
        fields = ('name', 'choice', 'tags')

exam/views.py
from django.shortcuts import render

# Create your views here.

from exam.models import *
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from exam.forms import *
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return redirect('exam:home')


@login_required
def home(request):
    import pdb
    # pdb.set_trace()
    print (request)
    name = "prashanth"
    date = datetime.datetime.now()

    # return HttpResponse("<h1>Hello %s, Time is %s</h1>" % (name, str(date)))
    return render(request, 'exam/home.html', {'name': name, 'date1': date})


@login_required
def contact(request):
    context = {'contact': 9959994410}
    return render(request, 'exam/contact.html', context)


@login_required
def about(request):
    context = {'info': 'This is the job providing website'}
    return render(request, 'exam/about.html', context)


@login_required
def questions_list(request):
    # import pdb; pdb.set_trace()
    if request.method == 'GET':
        questions = Question.objects.all()
        return render(request, 'exam/question-list.html',
                      {'questions': questions})
    return redirect('exam:home')


@login_required
def delete_question(request, id=None):
    if request.method == 'POST':
        question_obj = Question.objects.filter(id=id).first()
        if question_obj:
            # question_obj.delete()
            return JsonResponse({'success': True,
                                 "message": "Question deleted successufully."})
        return JsonResponse({'success': False,
                             "message": "Question Not Found."})
    return redirect('exam:home')


@login_required
def create_question(request):
    if request.method == 'GET':
        # import pdb; pdb.set_trace()
        question_create_form = QuestionForm()
        return render(request, 'exam/create_question.html',
                      {'question_create_form': question_create_form})

    elif request.method == 'POST':
        question_create_form = QuestionForm(request.POST)
        if question_create_form.is_valid():
            question_obj = question_create_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Question Created Successfully!.')
            return redirect(reverse('exam:update_question', kwargs={'id': question_obj.id}))
        else:
            messages.add_message(request, messages.ERROR,
                                 'Something Went Wrong!.')
            return render(request, 'exam/create_question.html',
                          {'question_create_form': question_create_form})
        return redirect('exam:home')


@login_required
def update_question(request, id):
    question_obj = Question.objects.filter(id=id).first()
    if not question_obj:
        messages.add_message(request, messages.ERROR,
                             'Question not found!.')
        return redirect('exam:questions_list')
    if request.method == 'GET':
        question_update_form = QuestionForm(instance=question_obj)
        return render(request, 'exam/update_question.html',
                      {'question_update_form': question_update_form})
    elif request.method == 'POST':
        question_update_form = QuestionForm(
            request.POST, instance=question_obj)
        if question_update_form.is_valid():
            question_obj = question_update_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Question Updated Successfully!.')
            return redirect(reverse('exam:update_question', kwargs={'id': question_obj.id}))
        else:
            messages.add_message(request, messages.ERROR,
                                 'Something Went Wrong!.')
            return render(request, 'exam/update_question.html',
                          {'question_update_form': question_update_form})
    return redirect('exam:questions_list')

exam/templates/exam/about.html
<html>
<head>
	<title>Job Ways</title>
</head>
<body>
		<h1>{{ info }}</h1>
		<a href="{% url 'exam:about' %}">Home</a>
		<a href="{% url 'exam:home' %}">Contacts</a>

</body>
</html>

exam/templates/exam/base.html
{% load staticfiles %}
{% load static %}

<html>
<head>
        <title>
            {% block title %}Exam{% endblock %}
        </title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
       <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        {# <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> #}

<!-- Latest compiled JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

      <!-- Boostrap Select picker -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.5.0/cloudinary-jquery-file-upload.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.5.0/cloudinary-jquery-file-upload.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static "css/app.css" %}">


<body>
  {% csrf_token %}

<nav class="navbar navbar-default">
  <div class="container-fluid" id="topheader">
    <ul class="nav navbar-nav admin_home_buttons" id="admin_home_buttons">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url 'exam:questions_list' %}">Questions</a></li>
      <li><a href="#">Exams</a></li>
      <li><a href="#">Assignments</a></li>
      <li><a href="#">Applicants</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li class="dropdown">
   <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> Hello {{ request.user }} <span class="caret"></span></a>
               <ul id="dropdown" class="dropdown-menu">
            <li><a href="#"> View Profile</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
          </ul>
      </li>
    </ul>
  </div>
</nav>

{% if messages %}
<div class="messages" id="loader">
    {% for message in messages %}
    <p id="menu_heading" style="font-weight: 200;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<div id="output">

  <div class="loading" id="menu_heading">
    {# <img src="{% static '/images/ajax-loader_final.gif' %}" alt="loading..."> #}
  </div>
</div>

<script type="text/javascript">

$(document).ready(function() {

  $('.loading').hide();
  // get current URL path and assign 'active' class
  var pathname = window.location.pathname;
  $('.active').removeClass('active');
  $('.nav > li > a[href="'+pathname+'"]').parent().addClass('active');
});
  function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}
    $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'))
                }
            }
        });

    // $('.logout').onclick(function(e){
    //   e.preventDefault()
    //   $.ajax({
    //         url: "http://localhost:8080/cp/signout/",
    //         method: "GET",
    //         processData: false,
    //         contentType: false,
    //         success: function(data) {
    //           $("[class$='_errors']").empty()
    //             if (data.success==true){
    //             }
    //             else{
    //               for(name in data.question_errors){
    //                 key='.'.concat(name,'_errors')
    //                 $(key).append(data.question_errors[name])
    //               }
    //               for(value in data.choice_errors){
    //                 key='.'.concat('choice_formset_errors')
    //                 $(key).append(data.choice_errors[value])
    //               }
    //               for(value in data.attachment_errors){
    //                 for(name in data.attachment_errors[value]){
    //                   key='.'.concat(name,'_errors')
    //                   $(key).empty()
    //                   $(key).append(data.attachment_errors[value][name][0])

    //                 }
    //               }
    //             }
    //           }
    //     });

    // });
</script>
<div class="container" id="ajaxbody">
{% block content %}

{% endblock %}
</div>
</body>

exam/templates/exam/contact.html
<html>
<head>
	<title>Job Ways</title>
</head>
<body>
		<h1>{{ contact }}</h1>
		<a href="{% url 'exam:home' %}">Home</a>
		<a href="{% url 'exam:about' %}">About</a>
</body>
</html>

exam/templates/exam/create_question.html
{% extends './base.html' %}
{% load staticfiles %}
{% load static %}
{% block content %}
	{% if error_message %}<p class="error_message"><strong>{{ error_message }}</strong></p>{% endif %}
	<form class="form-horizontal create_question" id="create_question" action="." method="post">
		{% csrf_token %}
		{% for field in question_create_form %}
		    <div class="form-group">
		      <label class="control-label col-sm-2" for="field">{{ field.label }} {{ form.errors }}</label>
		      <div class="col-sm-4">
				{{ field }}
				<p class="{{ field.name }}_errors">{{ field.errors }}</p>
				</div>
		    </div>
		{% endfor %}
		<button class="btn btn-default clear-all" type="reset">Clear</button>&nbsp;&nbsp;
		<button class="submit-button" type="submit">Create</button>
	</form>

	<script type="text/javascript">
		$( document ).ready(function() {
			$('.select2').select2();
		});
	</script>

{% endblock %}

exam/templates/exam/home.html
{% extends "./base.html" %}

exam/templates/exam/question-list.html
{% extends './base.html' %}
{% load staticfiles %}
{% load static %}
{% block content %}
	<a href="{% url 'exam:create_question' %}" class="create_question btn btn-success glyphicon glyphicon-plus" style="float:right;"></a>
	<table class='table table-striped'>
		<thead>
			<tr>
				<th>Name</th>
				<th>Choice</th>
				<th>Update Date</th>
				<th>Action</th>

			</tr>
		</thead>
		<tbody>
			{% for question in questions %}
				<tr>
					<td><a href="{% url 'exam:update_question' question.id %}">{{ question.name }}</a></td>
					<td>{{ question.choice|default_if_none:" - " }}</td>
					<td>{{ question.update_date }}</td>
					<td>
						<button class="btn delete_question glyphicon glyphicon-trash" question-url="{% url 'exam:delete_question'  question.id %}">
                        </button>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<script type="text/javascript">
		$( document ).ready(function() {
		    $('.delete_question').on('click', function(e){
		    	e.preventDefault()
		    	var question_url = $(this).attr("question-url")
		    	console.log(question_url)
		    	$.ajax({
		    		url: question_url,
		    		type:"post",
		    		success: function(result){
		    			if (result.success){
		    				alert(result.message)
		    			}
		    			else{
		    				alert(result.message)
		    			}
				 }});
		    })
		});
	</script>
{% endblock %}

exam/templates/exam/update_question.html
{% extends './base.html' %}
{% load staticfiles %}
{% load static %}
{% block content %}
	<form class="form-horizontal create_question" id="create_question" action="." method="post">
		{% csrf_token %}
		{% for field in question_update_form %}
		    <div class="form-group">
		      <label class="control-label col-sm-2" for="field">{{ field.label }} {{ form.errors }}</label>
		      <div class="col-sm-4">
				{{ field }}
				<p class="{{ field.name }}_errors">{{ field.errors }}</p>
				</div>
		    </div>
		{% endfor %}
		<button class="btn btn-default clear-all" type="reset">Clear</button>&nbsp;&nbsp;
		<button class="submit-button" type="submit">Update</button>
	</form>

	<script type="text/javascript">
		$( document ).ready(function() {
			$('.select2').select2();
		});
	</script>

{% endblock %}